"""interview, notification, savedvacancy

Revision ID: 14c05c66db97
Revises: fe38361646dc
Create Date: 2026-03-04 12:29:52.660354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c05c66db97'
down_revision: Union[str, Sequence[str], None] = 'fe38361646dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interview_format_enum = postgresql.ENUM(
        "ONLINE",
        "ONSITE",
        "PHONE",
        name="interview_format",
        create_type=False,
    )
    interview_status_enum = postgresql.ENUM(
        "PLANNED",
        "COMPLETED",
        "CANCELED",
        "NO_SHOW",
        name="interview_status",
        create_type=False,
    )
    interview_format_enum.create(op.get_bind(), checkfirst=True)
    interview_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "ix_notifications_user_read_created_at",
        "notifications",
        ["user_id", "is_read", "created_at"],
        unique=False,
    )
    op.create_table('saved_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_saved_vacancy_user_vacancy')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('format', postgresql.ENUM('ONLINE', 'ONSITE', 'PHONE', name='interview_format', create_type=False), nullable=False),
    sa.Column('location_or_link', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'COMPLETED', 'CANCELED', 'NO_SHOW', name='interview_status', create_type=False), server_default=sa.text("'PLANNED'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interview_format_enum = postgresql.ENUM(
        "ONLINE",
        "ONSITE",
        "PHONE",
        name="interview_format",
        create_type=False,
    )
    interview_status_enum = postgresql.ENUM(
        "PLANNED",
        "COMPLETED",
        "CANCELED",
        "NO_SHOW",
        name="interview_status",
        create_type=False,
    )

    op.drop_table('interviews')
    op.drop_table('saved_vacancies')
    op.drop_index("ix_notifications_user_read_created_at", table_name="notifications")
    op.drop_table('notifications')
    interview_status_enum.drop(op.get_bind(), checkfirst=True)
    interview_format_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
