"""empty message

Revision ID: 1e39790bf5bd
Revises: cf08d5f06f58
Create Date: 2026-02-11 14:31:23.109817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e39790bf5bd'
down_revision: Union[str, Sequence[str], None] = 'cf08d5f06f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.CheckConstraint("lang IN ('en','es')", name='check_vt_lang_en_es'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'lang', name='uq_vt_vacancy_lang')
    )
    op.create_index('ix_vt_vacancy_lang', 'vacancy_translations', ['vacancy_id', 'lang'], unique=False)
    op.create_unique_constraint('uq_application_resume_vacancy', 'applications', ['resume_id', 'vacancy_id'])
    op.drop_constraint(op.f('employers_company_id_fkey'), 'employers', type_='foreignkey')
    op.create_foreign_key(None, 'employers', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.create_foreign_key(op.f('employers_company_id_fkey'), 'employers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_application_resume_vacancy', 'applications', type_='unique')
    op.drop_index('ix_vt_vacancy_lang', table_name='vacancy_translations')
    op.drop_table('vacancy_translations')
    # ### end Alembic commands ###
