"""student-table

Revision ID: cf08d5f06f58
Revises: 2ed073be4f93
Create Date: 2026-01-17 19:31:33.195609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf08d5f06f58'
down_revision: Union[str, Sequence[str], None] = '2ed073be4f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('faculty', sa.String(length=255), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('employers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('vacancies_company_id_fkey'), 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('vacancies_company_id_fkey'), 'vacancies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employers', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('students')
    # ### end Alembic commands ###
